2025-10-06 20:31:53,527 ERROR: Exception on /index [GET] [in /home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/app/routes.py", line 39, in index
    return render_template('index.html', title='Home', form=form,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/matthew/projects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/matthew/projects/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/app/templates/index.html", line 20, in block 'content'
    {% include '_post.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/app/templates/_post.html", line 5, in top-level template code
    <a href="{{ url_for(user, username=post.author.username) }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1068, in url_for
    if endpoint[:1] == ".":
       ~~~~~~~~^^^^
jinja2.exceptions.UndefinedError: 'user' is undefined
2025-10-06 20:33:26,382 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:44]
2025-10-06 20:58:51,537 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:03:16,483 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:04:19,241 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:13:22,180 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:13:22,215 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:13:22,215 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:14:53,007 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:14:53,019 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:14:53,019 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:15:58,895 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:15:58,919 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:15:58,919 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:17:43,986 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:17:44,016 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:17:44,016 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:19:00,253 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:19:00,266 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:19:00,266 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:37:33,457 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:37:33,492 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:37:33,492 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:37:40,589 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:37:40,625 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:37:40,625 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:38:22,761 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:38:20,673 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:38:20,673 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:38:29,847 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:39:22,850 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:43:52,035 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-06 21:44:24,771 ERROR: Exception on /reset_password_request [POST] [in /home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 540, in send
    message.send(connection)
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 482, in send
    connection.send(self)
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 177, in send
    self.host.sendmail(
  File "/usr/lib/python3.12/smtplib.py", line 861, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python3.12/smtplib.py", line 611, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
                   ^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 451, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/lib/python3.12/smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "/usr/lib/python3.12/smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/projects/microblog/app/routes.py", line 194, in reset_password_request
    send_password_reset_email(user)
  File "/home/matthew/projects/microblog/app/email.py", line 14, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/home/matthew/projects/microblog/app/email.py", line 10, in send_email
    mail.send(msg)
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 539, in send
    with self.connect() as connection:
  File "/home/matthew/projects/microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 136, in __exit__
    self.host.quit()
  File "/usr/lib/python3.12/smtplib.py", line 993, in quit
    res = self.docmd("quit")
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.12/smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "/usr/lib/python3.12/smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2025-10-06 21:48:40,513 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-08 20:13:10,041 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-08 20:16:38,467 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
2025-10-08 20:29:49,572 INFO: Microblog startup [in /home/matthew/projects/microblog/app/__init__.py:47]
